// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gstok_api.Database;

#nullable disable

namespace gstok_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707201122_AddUsuarioNmPessoa")]
    partial class AddUsuarioNmPessoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gstok_api.Models.ClienteModel", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.HasKey("IdCliente");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("gstok_api.Models.EstoqueModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NmCor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nm_cor");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("QtEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("qt_estoque");

                    b.Property<string>("TpTamanho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tp_tamanho");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("estoque");
                });

            modelBuilder.Entity("gstok_api.Models.FotoPessoaModel", b =>
                {
                    b.Property<Guid>("IdFotoPessoa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_foto_pessoa");

                    b.Property<string>("NmImagem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nm_imagem");

                    b.Property<int>("NrAltura")
                        .HasColumnType("integer")
                        .HasColumnName("nr_altura");

                    b.Property<int>("NrLargura")
                        .HasColumnType("integer")
                        .HasColumnName("nr_largura");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.Property<string>("UrImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ur_imagem");

                    b.HasKey("IdFotoPessoa");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("foto_pessoa");
                });

            modelBuilder.Entity("gstok_api.Models.ImagemProdutoModel", b =>
                {
                    b.Property<Guid>("IdImagemProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_imagem_produto");

                    b.Property<bool>("FlPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_principal");

                    b.Property<string>("NmCaption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nm_caption");

                    b.Property<int>("NrAlturaAvatar")
                        .HasColumnType("integer")
                        .HasColumnName("nr_altura_avatar");

                    b.Property<int>("NrAlturaDesktop")
                        .HasColumnType("integer")
                        .HasColumnName("nr_altura_desktop");

                    b.Property<int>("NrAlturaMobile")
                        .HasColumnType("integer")
                        .HasColumnName("nr_altura_mobile");

                    b.Property<int>("NrAlturaTablet")
                        .HasColumnType("integer")
                        .HasColumnName("nr_altura_tablet");

                    b.Property<int>("NrAlturaThumbnail")
                        .HasColumnType("integer")
                        .HasColumnName("nr_altura_thumbnail");

                    b.Property<int>("NrLarguraAvatar")
                        .HasColumnType("integer")
                        .HasColumnName("nr_largura_avatar");

                    b.Property<int>("NrLarguraDesktop")
                        .HasColumnType("integer")
                        .HasColumnName("nr_largura_desktop");

                    b.Property<int>("NrLarguraMobile")
                        .HasColumnType("integer")
                        .HasColumnName("nr_largura_mobile");

                    b.Property<int>("NrLarguraTablet")
                        .HasColumnType("integer")
                        .HasColumnName("nr_largura_tablet");

                    b.Property<int>("NrLarguraThumbnail")
                        .HasColumnType("integer")
                        .HasColumnName("nr_largura_thumbnail");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("SqOrdem")
                        .HasColumnType("integer")
                        .HasColumnName("sq_ordem");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.Property<string>("UrAvatar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ur_avatar");

                    b.Property<string>("UrDesktop")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ur_desktop");

                    b.Property<string>("UrMobile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ur_mobile");

                    b.Property<string>("UrTablet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ur_tablet");

                    b.Property<string>("UrThumbnail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ur_thumbnail");

                    b.HasKey("IdImagemProduto");

                    b.HasIndex("ProdutoId");

                    b.ToTable("imagem_produto");
                });

            modelBuilder.Entity("gstok_api.Models.ItemVendaModel", b =>
                {
                    b.Property<Guid>("IdItemVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_item_venda");

                    b.Property<Guid>("EstoqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("estoque_id");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.Property<int>("QtQuantidade")
                        .HasColumnType("integer")
                        .HasColumnName("qt_quantidade");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.Property<decimal>("VlTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_total");

                    b.Property<decimal>("VlUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_unitario");

                    b.HasKey("IdItemVenda");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("VendaId");

                    b.ToTable("item_venda");
                });

            modelBuilder.Entity("gstok_api.Models.VendaModel", b =>
                {
                    b.Property<Guid>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_venda");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("StPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("st_pagamento");

                    b.Property<string>("StVenda")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("st_venda");

                    b.Property<string>("TpPagamento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tp_pagamento");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.Property<decimal>("VlDesconto")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_desconto");

                    b.Property<decimal>("VlFrete")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_frete");

                    b.Property<decimal>("VlSubtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_subtotal");

                    b.Property<decimal>("VlTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_total");

                    b.HasKey("IdVenda");

                    b.HasIndex("ClienteId");

                    b.ToTable("venda");
                });

            modelBuilder.Entity("gstok_api.Models.PessoaModel", b =>
                {
                    b.Property<Guid>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pessoa");

                    b.Property<string>("CdInscricaoNacional")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cd_inscricao_nacional");

                    b.Property<string>("NmEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nm_email");

                    b.Property<string>("NmPessoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_pessoa");

                    b.Property<string>("NmSobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_sobrenome");

                    b.Property<string>("NmTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nm_telefone");

                    b.Property<string>("TpPessoa")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tp_pessoa");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.HasKey("IdPessoa");

                    b.HasIndex("CdInscricaoNacional")
                        .IsUnique();

                    b.ToTable("pessoa");
                });

            modelBuilder.Entity("gstok_api.Models.ProdutoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CdSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cd_sku");

                    b.Property<string>("DsProduto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_produto");

                    b.Property<bool>("FlAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<string>("NmMarca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_marca");

                    b.Property<string>("NmProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nm_produto");

                    b.Property<Guid?>("TipoProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_produto_id");

                    b.Property<string>("TpEstacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tp_estacao");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.Property<decimal>("VlPreco")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_preco");

                    b.Property<decimal>("VlVenda")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_venda");

                    b.HasKey("Id");

                    b.HasIndex("TipoProdutoId");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("gstok_api.Models.SessaoModel", b =>
                {
                    b.Property<Guid>("IdSessao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_sessao");

                    b.Property<string>("CdToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cd_token");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime>("TsExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_expiracao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("IdSessao");

                    b.HasIndex("CdToken")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("sessao");
                });

            modelBuilder.Entity("gstok_api.Models.TipoProdutoModel", b =>
                {
                    b.Property<Guid>("IdTipoProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tipo_produto");

                    b.Property<string>("NmTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_tipo");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.HasKey("IdTipoProduto");

                    b.HasIndex("NmTipo")
                        .IsUnique();

                    b.ToTable("tipo_produto");
                });

            modelBuilder.Entity("gstok_api.Models.UsuarioModel", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("DsSenha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_senha");

                    b.Property<string>("NmEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nm_email");

                    b.Property<string>("NmPessoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_pessoa");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime>("TsCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_criacao");

                    b.Property<DateTime?>("TsEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_edicao");

                    b.HasKey("IdUsuario");

                    b.HasIndex("NmEmail")
                        .IsUnique();

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasFilter("pessoa_id IS NOT NULL");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("gstok_api.Models.ClienteModel", b =>
                {
                    b.HasOne("gstok_api.Models.PessoaModel", "Pessoa")
                        .WithOne("Cliente")
                        .HasForeignKey("gstok_api.Models.ClienteModel", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("gstok_api.Models.EstoqueModel", b =>
                {
                    b.HasOne("gstok_api.Models.ProdutoModel", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("gstok_api.Models.FotoPessoaModel", b =>
                {
                    b.HasOne("gstok_api.Models.PessoaModel", "Pessoa")
                        .WithOne("Foto")
                        .HasForeignKey("gstok_api.Models.FotoPessoaModel", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("gstok_api.Models.ImagemProdutoModel", b =>
                {
                    b.HasOne("gstok_api.Models.ProdutoModel", "Produto")
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("gstok_api.Models.ItemVendaModel", b =>
                {
                    b.HasOne("gstok_api.Models.EstoqueModel", "Estoque")
                        .WithMany()
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gstok_api.Models.VendaModel", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("gstok_api.Models.VendaModel", b =>
                {
                    b.HasOne("gstok_api.Models.ClienteModel", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("gstok_api.Models.ProdutoModel", b =>
                {
                    b.HasOne("gstok_api.Models.TipoProdutoModel", "TipoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TipoProduto");
                });

            modelBuilder.Entity("gstok_api.Models.SessaoModel", b =>
                {
                    b.HasOne("gstok_api.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("gstok_api.Models.UsuarioModel", b =>
                {
                    b.HasOne("gstok_api.Models.PessoaModel", "Pessoa")
                        .WithOne()
                        .HasForeignKey("gstok_api.Models.UsuarioModel", "PessoaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("gstok_api.Models.ClienteModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("gstok_api.Models.VendaModel", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("gstok_api.Models.PessoaModel", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("gstok_api.Models.ProdutoModel", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("gstok_api.Models.TipoProdutoModel", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
