// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gstok_api.Database;

#nullable disable

namespace gstok_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629234448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gstok_api.Models.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NmCor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nm_cor");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("QtEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("qt_estoque");

                    b.Property<string>("TpTamanho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tp_tamanho");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("estoque");
                });

            modelBuilder.Entity("gstok_api.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NmEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nm_email");

                    b.Property<string>("NmPessoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_pessoa");

                    b.Property<string>("NmSobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_sobrenome");

                    b.Property<string>("NmTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nm_telefone");

                    b.Property<string>("NrCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("nr_cpf");

                    b.HasKey("Id");

                    b.ToTable("pessoa");
                });

            modelBuilder.Entity("gstok_api.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CdSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cd_sku");

                    b.Property<string>("DsProduto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_produto");

                    b.Property<DateOnly>("DtCriacao")
                        .HasColumnType("date")
                        .HasColumnName("dt_criacao");

                    b.Property<DateOnly?>("DtEdicao")
                        .HasColumnType("date")
                        .HasColumnName("dt_edicao");

                    b.Property<bool>("FlAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<string>("NmMarca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nm_marca");

                    b.Property<string>("NmProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nm_produto");

                    b.Property<decimal>("VlPreco")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_preco");

                    b.Property<decimal>("VlVenda")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_venda");

                    b.HasKey("Id");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("gstok_api.Models.Estoque", b =>
                {
                    b.HasOne("gstok_api.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("gstok_api.Models.Produto", b =>
                {
                    b.Navigation("Estoques");
                });
#pragma warning restore 612, 618
        }
    }
}
